### ISSUE TITLE
bug: Wrong classification

### ISSUE THREAD

**Issue by IceWizard4902** [baobaybong/phuong-classifier#3]
I don't think your application works properly with this input

<img width="212" alt="image" src="https://github.com/baobaybong/phuong-classifier/assets/77266084/23ce9611-995f-4ab7-a905-086737f526a4">

Please fix ASAP @baobaybong

**Comment by baobaybong** [comment]
Works fine. Please try again.

**Comment by IceWizard4902** [comment]
Skill issue. My bad
